add github ci11  workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,8 +22,18 @@ jobs:
 
       - name: Start FastAPI server
         run: |
-          uvicorn app:app --host 0.0.0.0 --port 8000 &
-          sleep 3
+          echo "Waiting for API to be ready on http://localhost:8080 ..."
+          for i in {1..10}; do
+            if curl -sSf http://localhost:8080/status/ > /dev/null; then
+              echo "API is up ✅"
+              exit 0
+            fi
+            echo "API not ready yet, retrying in 3s..."
+            sleep 3
+          done
+          echo "API failed to start ❌"
+          docker logs fee-service || true
+          exit 1
 
       - name: Test GET /
         run: curl -f http://localhost:8000/
